In [23]:
import pandas as pd
from IPython.display import display


df = pd.read_excel(r'C:\\Users\\danme\\OneDrive\\Documentos\\GitHub\\Tensor_flow_keras_test\\Auto.ipynb\\Notas_3_trimestre.xlsx',header = 1 )
display(df)

,Nomes:,Notas 1,Notas 2,N final,Observações,Email
0,Aline Alves,2.5,3,NaN,nada,danfdts10@gmail.com
1,Ana Luisa,2.8,2.3,NaN,nada,danfdts10@gmail.com
2,Arthur Loyola,2.8,2.5,NaN,nada,danfdts10@gmail.com
3,Bruno,3,2,NaN,isso,danfdts10@gmail.com
4,Felipe Oliveira,3,3,NaN,isso,danfdts10@gmail.com
5,João Gabriel,2.4,1.6,NaN,nada,danfdts10@gmail.com
6,Kaun Azevedo,3,3,NaN,nada,danfdts10@gmail.com
7,Mariana Malheiro,2.3,3,NaN,nada,danfdts10@gmail.com
8,Miguel Vieira,2,2,NaN,im,danfdts10@gmail.com
9,Pedro Lucas,2.8,2.8,NaN,sn,danfdts10@gmail.com
10,Pedro Reis,3,3,NaN,s,danfdts10@gmail.com
11,Renato Nascimento,1.8,2,NaN,s,danfdts10@gmail.com
12,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,Nomes:,Notas 1,Notas 2,N final,NaN,NaN
16,Mariana Malheiro,2.8,3,NaN,NaN,NaN
17,Stephanie,2.8,2.2,NaN,NaN,NaN
18,Kaun Azevedo,3,3,NaN,NaN,NaN
19,Fernanda de Souza,2.5,3,NaN,NaN,NaN
20,Carlos Henrique,2.6,2.3,NaN,NaN,NaN
21,Pedro Henrique,3,2.5,NaN,NaN,NaN
22,Grazielly Ramos,3,2,NaN,NaN,NaN
23,Pedro Lucas,2.8,2,NaN,NaN,NaN
24,Renato Nascimento,2.2,1.5,NaN,NaN,NaN
25,Ana luiza Felício,3,2,NaN,NaN,NaN
26,Raphaela Soares,3,3,NaN,NaN,NaN
27,Vladmir,3,3,NaN,NaN,NaN
28,Orion,2.5,3,NaN,NaN,NaN
29,Arthur Loyola,2.8,3,NaN,NaN,NaN
30,Gustavo,2.7,3,NaN,NaN,NaN
31,Lucas,2.7,2.5,NaN,NaN,NaN

In [18]:
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Configurações do servidor SMTP
smtp_server = 'smtp.gmail.com'
smtp_port = 587
remetente = 'danfdts10@gmail.com'
senha = 'geif cejg qjkj faez'

server = smtplib.SMTP(smtp_server, smtp_port)
server.starttls()
server.login(remetente, senha)

(235, b'2.7.0 Accepted')

In [ ]:
df.rename(columns={'E-mail': 'Email', 'Observação': 'Observações'}, inplace=True)
df = df.drop('column 4', axis=1, errors='ignore')
df_sem_na = df.dropna()
df_sem_na_colunas = df.dropna(axis=1)
display(df)

                Nomes: Notas 1 Notas 2 Observações                Email
0          Aline Alves     2.5       3       nada   danfdts10@gmail.com
1           Ana Luisa      2.8     2.3       nada   danfdts10@gmail.com
2        Arthur Loyola     2.8     2.5       nada   danfdts10@gmail.com
3                Bruno       3       2        isso  danfdts10@gmail.com
4      Felipe Oliveira       3       3        isso  danfdts10@gmail.com
5         João Gabriel     2.4     1.6        nada  danfdts10@gmail.com
6         Kaun Azevedo       3       3       nada   danfdts10@gmail.com
7     Mariana Malheiro     2.3       3       nada   danfdts10@gmail.com
8       Miguel Vieira        2       2          im  danfdts10@gmail.com
9          Pedro Lucas     2.8     2.8          sn  danfdts10@gmail.com
10          Pedro Reis       3       3           s  danfdts10@gmail.com
11  Renato Nascimento      1.8       2           s  danfdts10@gmail.com